---

- name: Setting Up The App
  hosts: app_server
  vars:
    DB_HOST: 172.31.32.102

  # Gathers state of machine before running
  gather_facts: yes

  # give root permissions
  become: yes

  tasks:
    - name: Update and upgrade installation
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx, nodejs, and npm
      apt:
        pkg:
          - nginx
          - git
          - nodejs
          - npm
        state: latest

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy template reverse_proxy
      copy:
        src: ~/intro-to-ansible/provisioning/templates/nginx/proxy_config.conf
        dest: /etc/nginx/sites-available/default

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Copy app
      copy:
        src: ~/intro-to-ansible/app
        dest: /home/ubuntu/
        owner: ubuntu
        group: ubuntu

    - name: Print DB_HOST variable
      debug:
        msg: "DB_HOST is {{ DB_HOST }}"

          # This block will set the DB_HOST
    - name: set db host as global variable
      shell: |
         export DB_HOST={{ DB_HOST }}
         sed -i '/export DB_HOST=/d' .bashrc
         printf '\nexport DB_HOST={{ DB_HOST }}' >> .bashrc
      args:
          chdir: /home/ubuntu

    - name: Install app using npm install
      npm:
        path: /home/ubuntu/app/
          # this become is needed apparently
      become: yes

    - name: Delete existing pm2 service
      # can change this to the `shell` module
      command: "pm2 delete app"
      ignore_errors: True
          # this become is needed apparently
      become: yes

    - name: Start the app in pm2
      # can change this to the `shell` module
      command: "DB_HOST={{ DB_HOST }} pm2 start /home/ubuntu/app/app.js --update-env"
          # this become is needed apparently
      become: yes

