---

- name: setting up the mongodb instance
  hosts: db_server

  # gathers state of machine before running
  gather_facts: yes

  # give root permissions
  become: yes

  tasks:
    - name: update and upgrade installation
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600


    - name: install version of mongodb in the ubuntu default repositories
      apt:
        pkg:
          mongodb-org
        state: present

    - name: change mongodb to listen on all ports
      # could use the `replace` module here instead
      shell: sudo sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
      notify: restart_db

    - name: Restart mongodb manually
      service:
        name: mongodb
        state: restarted

          #   handlers:
          #     - name: restart_db
          #       service:
          #         name: mongodb
          #         state: restarted
