---

- name: Setting up the mongodb instance
  hosts: db_server

  # gathers state of machine before running
  gather_facts: yes

  # give root permissions
  become: yes

  tasks:
    - name: update and upgrade installation
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600

    - name: Getting MongoDB key from official servers
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Adding the MongoDB repository to source list
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: "mongodb-org-3.2"
        update_cache: yes

    - name: Installing MongoDB 3.2.20
      apt:
        name: mongodb-org=3.2.20
        state: present
        force: yes

    - name: change mongodb to listen on all ports
      # could use the `replace` module here instead
      shell: sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
      warn: false
      notify: restart_db

  handlers:
  - name: restart_db
    service:
       name: mongod
       state: restarted
