---

- hosts: app_server

  # Gathers state of machine before running
  gather_facts: yes

  # give root permissions
  become: true

  tasks:
    - name: Update and upgrade installation
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx, nodejs, and npm
      apt:
        pkg:
          - nginx
          - nodejs
          - npm
        state: latest

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy template reverse_proxy
      copy:
        src: ~/intro-to-ansible/provisioning/templates/nginx/proxy_config.conf
        dest: /etc/nginx/sites-available/default

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Copy app
      copy:
        src: ~/intro-to-ansible/provisioning/app
        dest: /home/ubuntu/

    - name: Install app
      npm:
        path: /home/ubuntu/app/package.json
        state: latest

    - name: Delete existing pm2 service
      command: "pm2 delete app"
      ignore_errors: True

    - name: Start the app in pm2
      command: "pm2 start /home/ubuntu/app/app.js --update-env"

